name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      TF_VAR_key_name: ${{ secrets.KEY_NAME }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.0

    - name: Terraform Init
      working-directory: .
      run: terraform init

    - name: Terraform Apply
      working-directory: .
      run: terraform apply -auto-approve

    - name: Wait for Instance to Stabilize
      run: sleep 60

    - name: Run Ansible Playbook
      uses: dawidd6/action-ansible-playbook@v2
      with:
        playbook: ansible/deploy.yml
        inventory: ansible/inventory.ini
        key: ${{ secrets.SSH_PRIVATE_KEY }}
