name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      TF_VAR_key_name: ${{ secrets.KEY_NAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Get instance IP from Terraform
        id: get_ip
        run: |
          echo "IP=$(terraform output -raw instance_public_ip)" >> "$GITHUB_ENV"

      - name: Generate inventory.ini
        run: |
          echo "[web]" > ansible/inventory.ini
          echo "slave1 ansible_ssh_host=${{ env.IP }} ansible_user=ubuntu" >> ansible/inventory.ini

      - name: Wait for Instance to Stabilize
        run: sleep 60

      - name: Debug Inventory File
        run: cat ansible/inventory.ini

      - name: Run Ansible Playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: ansible/deploy.yml
          inventory: ansible/inventory.ini
          key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Wait for 3 minutes before destroy
        run: sleep 180

      - name: Destroy Terraform
        run: terraform destroy -auto-approve
